FROM python:3.9-slim

WORKDIR .

COPY requirements.txt requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt

EXPOSE 5005

COPY . .
RUN  python3 -m grpc_tools.protoc -I./ --python_out=./ --grpc_python_out=./ location.proto
CMD ["python", "grpc_kafka_producer.py"]